version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: omgupta2202
      MONGO_INITDB_ROOT_PASSWORD: hGZFXBseaREbAJAq

  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
